# Generated by Django 5.1.3 on 2026-03-29 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=300)),
                ('department_short_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('pub_type', models.CharField(choices=[('article', 'Статья'), ('monograph', 'Монография')], max_length=50)),
            ],
            options={
                'db_table': 'publication',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('position', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('is_phd_student', models.BooleanField(default=False)),
                ('academic_degree', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='api.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='api.userrole')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='KPIGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('metric_group', models.CharField(blank=True, max_length=50, null=True)),
                ('base_points', models.FloatField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_groups', to='api.department')),
            ],
            options={
                'db_table': 'kpi_group',
            },
        ),
        migrations.CreateModel(
            name='KPIWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('group_weight', models.FloatField()),
                ('weight', models.FloatField()),
                ('kpi_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='api.kpigroup')),
            ],
            options={
                'db_table': 'kpi_weight',
            },
        ),
        migrations.CreateModel(
            name='Monograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('pages_count', models.IntegerField(blank=True, null=True)),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monograph', to='api.publication')),
            ],
            options={
                'db_table': 'monograph',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.CharField(max_length=200)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('quartile', models.IntegerField(blank=True, null=True)),
                ('is_scopus', models.BooleanField(default=False)),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='api.publication')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='ScientificWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('work_type', models.CharField(max_length=50)),
                ('points', models.FloatField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_works', to='api.employee')),
            ],
            options={
                'db_table': 'scientific_work',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='scientific_work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='api.scientificwork'),
        ),
        migrations.CreateModel(
            name='ProjectParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('scientific_work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_participation', to='api.scientificwork')),
            ],
            options={
                'db_table': 'project_participation',
            },
        ),
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('defense_date', models.DateField(blank=True, null=True)),
                ('scientific_work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dissertation', to='api.scientificwork')),
            ],
            options={
                'db_table': 'dissertation',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('is_commercial', models.BooleanField(default=False)),
                ('scientific_work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='software', to='api.scientificwork')),
            ],
            options={
                'db_table': 'software',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Назначена'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('overdue', 'Просрочена')], default='assigned', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='api.employee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='api.employee')),
                ('kpi_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.kpigroup')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('scientific', 'Научная'), ('organizational', 'Организационная'), ('technical', 'Техническая')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='api.employee')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='api.employee')),
            ],
            options={
                'db_table': 'verification_request',
            },
        ),
        migrations.CreateModel(
            name='TechnicalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('work_date', models.DateField()),
                ('metric', models.CharField(blank=True, max_length=50, null=True)),
                ('base_points', models.FloatField(default=0)),
                ('points', models.FloatField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_works', to='api.employee')),
                ('verification_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_works', to='api.verificationrequest')),
            ],
            options={
                'db_table': 'technical_work',
            },
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='verification_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_works', to='api.verificationrequest'),
        ),
        migrations.CreateModel(
            name='OrganizationalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('work_type', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('participants_count', models.IntegerField(blank=True, null=True)),
                ('points', models.FloatField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizational_works', to='api.employee')),
                ('verification_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizational_works', to='api.verificationrequest')),
            ],
            options={
                'db_table': 'organizational_work',
            },
        ),
        migrations.CreateModel(
            name='KPIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('scientific_score', models.FloatField(default=0)),
                ('organizational_score', models.FloatField(default=0)),
                ('technical_score', models.FloatField(default=0)),
                ('total_ipi', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_results', to='api.employee')),
            ],
            options={
                'db_table': 'kpi_result',
                'unique_together': {('employee', 'year', 'quarter')},
            },
        ),
    ]
