# Generated by Django 5.1.3 on 2026-03-30 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpigroup',
            name='base_points',
        ),
        migrations.RemoveField(
            model_name='kpigroup',
            name='metric_group',
        ),
        migrations.AddField(
            model_name='kpigroup',
            name='group_weight',
            field=models.FloatField(default=1.0, help_text='Wi — вес группы'),
        ),
        migrations.CreateModel(
            name='KPIIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название показателя', max_length=200)),
                ('work_type_key', models.CharField(help_text='Ключ для сопоставления с work_type работ', max_length=100)),
                ('weight', models.FloatField(default=1.0, help_text='Wij — вес показателя')),
                ('kpi_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='api.kpigroup')),
            ],
            options={
                'db_table': 'kpi_indicator',
            },
        ),
        migrations.DeleteModel(
            name='KPIWeight',
        ),
    ]
