# Generated by Django 5.1.3 on 2026-04-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_kpigroup_base_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalwork',
            name='work_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
