# Generated by Django 5.1.3 on 2026-04-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_project_and_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='work_type_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
