# Generated by Django 5.1.3 on 2026-04-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project_completed_at_task_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_phd_student',
        ),
        migrations.AddField(
            model_name='employee',
            name='phd_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_type',
            field=models.CharField(choices=[('junior_researcher', 'м.н.с.'), ('researcher', 'н.с.'), ('senior_researcher', 'с.н.с.'), ('engineer', 'инженер'), ('phd_student', 'аспирант')], default='researcher', max_length=32),
        ),
    ]
