# Generated by Django 5.1.3 on 2026-04-25 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_employee_is_phd_student_employee_phd_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position_type',
            field=models.CharField(choices=[('junior_researcher', 'м.н.с.'), ('researcher', 'н.с.'), ('senior_researcher', 'с.н.с.'), ('engineer', 'инженер'), ('phd_student', 'аспирант'), ('head', 'руководитель отдела')], default='researcher', max_length=32),
        ),
        migrations.AlterField(
            model_name='kpiindicator',
            name='weight',
            field=models.FloatField(default=1.0, help_text='W_base — базовый вес показателя'),
        ),
        migrations.CreateModel(
            name='KPIGroupWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(choices=[('junior_researcher', 'м.н.с.'), ('researcher', 'н.с.'), ('senior_researcher', 'с.н.с.'), ('engineer', 'инженер'), ('phd_student', 'аспирант'), ('head', 'руководитель отдела')], max_length=32)),
                ('phd_year', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(default=1.0)),
                ('kpi_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_weights', to='api.kpigroup')),
            ],
            options={
                'db_table': 'kpi_group_weight',
                'unique_together': {('kpi_group', 'position_type', 'phd_year')},
            },
        ),
    ]
