# Generated by Django 5.1.3 on 2026-05-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_employee_position_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('k_age', 'Поправка по возрасту'), ('k_experience', 'Поправка по стажу научной работы'), ('k_phd', 'Поправка по году обучения в аспирантуре'), ('quartile', 'Множитель квартиля журнала')], max_length=20)),
                ('description', models.CharField(help_text='Текстовое описание правила', max_length=300)),
                ('min_value', models.IntegerField(blank=True, help_text='Нижняя граница диапазона (включительно), либо NULL', null=True)),
                ('max_value', models.IntegerField(blank=True, help_text='Верхняя граница диапазона (включительно), либо NULL', null=True)),
                ('coefficient', models.FloatField(default=1.0, help_text='Итоговый коэффициент / множитель')),
                ('priority', models.IntegerField(default=100, help_text='Порядок проверки (меньше — раньше)')),
            ],
            options={
                'db_table': 'rule',
                'ordering': ['rule_type', 'priority'],
            },
        ),
    ]
