# Generated by Django 5.1.3 on 2026-05-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiindicator',
            name='entity_kind',
            field=models.CharField(choices=[('none', 'Без дополнительных полей'), ('article', 'Статья'), ('monograph', 'Монография'), ('dissertation', 'Диссертация'), ('software', 'ПО'), ('grant', 'Участие в проекте')], default='none', help_text='Тип сущности-подтипа научной работы (для других категорий — none)', max_length=20),
        ),
    ]
